"""initial_schema

Revision ID: 261466931cbd
Revises: 
Create Date: 2026-03-26 18:31:16.006934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '261466931cbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('condition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_days', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('client_type', sa.String(length=30), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('ticker_mw', sa.String(length=20), nullable=True),
    sa.Column('ticker_yf', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('currency_exposure', sa.String(length=5), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('domicile_country', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_mw')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_log_date', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_type', name='uq_dashboard_widget_type')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=5), nullable=False),
    sa.Column('to_currency', sa.String(length=5), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name='uq_exchange_rate')
    )
    op.create_index('idx_exchange_rate_date', 'exchange_rates', ['rate_date'], unique=False)
    op.create_index('idx_exchange_rate_pair', 'exchange_rates', ['from_currency', 'to_currency'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('mw_date_from', sa.Date(), nullable=True),
    sa.Column('mw_date_to', sa.Date(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('trigger_source', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_batches_status', 'import_batches', ['status'], unique=False)
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticker_yf', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('index_type', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default_benchmark', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_yf')
    )
    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_investments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_savings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('savings_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('category_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_monthly_summary')
    )
    op.create_index('idx_monthly_summaries_period', 'monthly_summaries', ['year', 'month'], unique=False)
    op.create_table('mw_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_internal_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_networth', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_internal_id')
    )
    op.create_table('mw_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_internal_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mw_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_internal_id')
    )
    op.create_table('net_worth_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reached_date', sa.Date(), nullable=True),
    sa.Column('is_reached', sa.Boolean(), nullable=False),
    sa.Column('milestone_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_net_worth', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('investment_portfolio_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash_and_bank_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('real_estate_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('pension_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_assets_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('change_eur', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', name='uq_networth_date')
    )
    op.create_index('idx_networth_date', 'net_worth_snapshots', ['snapshot_date'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_date', 'notes', ['created_at'], unique=False)
    op.create_index('idx_notes_entity', 'notes', ['entity_type', 'entity_id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective_type', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('funding_source', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('parameter_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_param_history_date', 'parameter_history', ['changed_at'], unique=False)
    op.create_index('idx_param_history_key', 'parameter_history', ['param_key'], unique=False)
    op.create_table('parameters',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_parameters_category', 'parameters', ['category'], unique=False)
    op.create_table('pension_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('plan_number', sa.String(length=100), nullable=True),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_contributions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_retirement_date', sa.Date(), nullable=True),
    sa.Column('risk_profile', sa.String(length=30), nullable=True),
    sa.Column('annual_return_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('include_in_networth', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_statement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('usage', sa.String(length=20), nullable=False),
    sa.Column('surface_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_costs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_valuation_date', sa.Date(), nullable=True),
    sa.Column('include_in_networth', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cadaster_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_type', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_tasks_status', 'scheduled_tasks', ['status'], unique=False)
    op.create_index('idx_scheduled_tasks_type', 'scheduled_tasks', ['task_type'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('simulation_type', sa.String(length=30), nullable=False),
    sa.Column('base_scenario_type', sa.String(length=20), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('initial_value_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simulations_active', 'simulations', ['is_active'], unique=False)
    op.create_table('social_security_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_date', sa.Date(), nullable=False),
    sa.Column('monthly_at_65', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_at_67', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_at_70', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contribution_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('regulatory_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('tag_scope', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('total_realized_gains', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_realized_losses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_taxable_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_tax_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_dividends_received', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_dividend_tax_withheld', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('asset_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_year', name='uq_tax_report_year')
    )
    op.create_table('user_preferences',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trigger_value', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_history_date', 'alert_history', ['triggered_at'], unique=False)
    op.create_index('idx_alert_history_rule', 'alert_history', ['alert_rule_id'], unique=False)
    op.create_index('idx_alert_history_status', 'alert_history', ['status'], unique=False)
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unrealized_pnl_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('weight_actual_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['net_worth_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'asset_id', name='uq_asset_snapshot')
    )
    op.create_index('idx_asset_snapshot_date', 'asset_snapshots', ['snapshot_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount_planned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mw_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year', 'month', name='uq_budget_category_month')
    )
    op.create_index('idx_budgets_period', 'budgets', ['year', 'month'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('ratio_from', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ratio_to', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corporate_actions_asset', 'corporate_actions', ['asset_id'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('mw_account_id', sa.Integer(), nullable=True),
    sa.Column('include_in_networth', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mw_account_id'], ['mw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('shares_held', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('amount_per_share', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dividend_type', sa.String(length=20), nullable=False),
    sa.Column('tax_withheld_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dividends_asset', 'dividends', ['asset_id'], unique=False)
    op.create_index('idx_dividends_date', 'dividends', ['payment_date'], unique=False)
    op.create_table('extraordinary_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('income_type', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expected_monthly_net', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mw_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_index_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('price_close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('daily_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['market_indices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'data_date', name='uq_market_index_data')
    )
    op.create_index('idx_market_index_data_date', 'market_index_data', ['index_id', 'data_date'], unique=False)
    op.create_table('monte_carlo_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('num_iterations', sa.Integer(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('p10_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p25_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p50_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p75_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('p90_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('probability_of_reaching_goal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paths_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortgages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('interest_rate_pct', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('reference_rate', sa.String(length=30), nullable=True),
    sa.Column('spread_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_term_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mw_payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_internal_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['mw_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_internal_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'tag_id', name='uq_note_tag')
    )
    op.create_table('pension_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_plan_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pension_plan_id'], ['pension_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pension_plan_id', 'valuation_date', name='uq_pension_valuation')
    )
    op.create_index('idx_pension_valuations_plan_date', 'pension_valuations', ['pension_plan_id', 'valuation_date'], unique=False)
    op.create_table('price_fetch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_returned', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_fetch_logs_date', 'price_fetch_logs', ['fetched_at'], unique=False)
    op.create_index('idx_price_fetch_logs_status', 'price_fetch_logs', ['status'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', name='uq_price_history')
    )
    op.create_index('idx_price_history_asset_date', 'price_history', ['asset_id', 'price_date'], unique=False)
    op.create_table('property_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_valuations_date', 'property_valuations', ['valuation_date'], unique=False)
    op.create_index('idx_property_valuations_property', 'property_valuations', ['property_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('annual_return', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'scenario_type', name='uq_scenario')
    )
    op.create_table('simulation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('param_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'param_key', name='uq_sim_param')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('projection_date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_contributed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_returns', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('asset_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'projection_date', name='uq_sim_result')
    )
    op.create_index('idx_sim_results_sim_date', 'simulation_results', ['simulation_id', 'projection_date'], unique=False)
    op.create_table('spending_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=30), nullable=False),
    sa.Column('average_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('std_deviation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sample_months', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mw_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'pattern_type', name='uq_spending_pattern')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(length=20), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('shares', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fees_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency_original', sa.String(length=5), nullable=True),
    sa.Column('amount_original', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mw_description', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_date', 'asset_id', 'amount_eur', 'shares', name='uq_transaction')
    )
    op.create_index('idx_transactions_asset_id', 'transactions', ['asset_id'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['mw_date'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['tx_type'], unique=False)
    op.create_table('credit_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_purchases', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_payments', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_account_id', 'statement_date', name='uq_credit_statement')
    )
    op.create_index('idx_credit_statements_account', 'credit_statements', ['credit_account_id'], unique=False)
    op.create_table('mw_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_internal_id', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('tx_type', sa.String(length=20), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('is_excluded_from_reports', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mw_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['mw_categories.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['mw_payees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_internal_id', name='uq_mw_transactions_mw_id')
    )
    op.create_index('idx_mw_tx_account', 'mw_transactions', ['account_id'], unique=False)
    op.create_index('idx_mw_tx_category', 'mw_transactions', ['category_id'], unique=False)
    op.create_index('idx_mw_tx_date', 'mw_transactions', ['tx_date'], unique=False)
    op.create_index('idx_mw_tx_type', 'mw_transactions', ['tx_type'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('expected_day_of_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('detection_source', sa.String(length=20), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mw_categories.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['mw_payees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_tx_id', sa.Integer(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('shares_acquired', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('shares_remaining', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('price_per_share_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_basis_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_lots_asset', 'tax_lots', ['asset_id'], unique=False)
    op.create_index('idx_tax_lots_open', 'tax_lots', ['asset_id', 'is_closed'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'tag_id', name='uq_transaction_tag')
    )
    op.create_table('credit_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['credit_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_payments_account', 'credit_payments', ['credit_account_id'], unique=False)
    op.create_index('idx_credit_payments_date', 'credit_payments', ['payment_date'], unique=False)
    op.create_table('income_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_source_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_withheld', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('social_security_withheld', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_sources.id'], ),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_records_date', 'income_records', ['received_date'], unique=False)
    op.create_index('idx_income_records_source', 'income_records', ['income_source_id'], unique=False)
    op.create_table('mortgage_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgages.id'], ),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mortgage_payments_date', 'mortgage_payments', ['payment_date'], unique=False)
    op.create_index('idx_mortgage_payments_mortgage', 'mortgage_payments', ['mortgage_id'], unique=False)
    op.create_table('mw_transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mw_transaction_id', 'tag_id', name='uq_mw_transaction_tag')
    )
    op.create_table('pension_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_plan_id', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contribution_type', sa.String(length=20), nullable=False),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.ForeignKeyConstraint(['pension_plan_id'], ['pension_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pension_contributions_date', 'pension_contributions', ['contribution_date'], unique=False)
    op.create_index('idx_pension_contributions_plan', 'pension_contributions', ['pension_plan_id'], unique=False)
    op.create_table('property_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deductible', sa.Boolean(), nullable=False),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_expenses_date', 'property_expenses', ['expense_date'], unique=False)
    op.create_index('idx_property_expenses_property', 'property_expenses', ['property_id'], unique=False)
    op.create_table('realized_gains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sale_tx_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_tx_id', sa.Integer(), nullable=True),
    sa.Column('tax_lot_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('sale_year', sa.Integer(), nullable=False),
    sa.Column('shares_sold', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('sale_price_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('acquisition_price_eur', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('gross_proceeds_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fees_eur', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gain_loss_eur', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_long_term', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['tax_lot_id'], ['tax_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_realized_gains_asset', 'realized_gains', ['asset_id'], unique=False)
    op.create_index('idx_realized_gains_sale_tx', 'realized_gains', ['sale_tx_id'], unique=False)
    op.create_index('idx_realized_gains_year', 'realized_gains', ['sale_year'], unique=False)
    op.create_table('rental_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tenant_name', sa.String(length=200), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('mw_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mw_transaction_id'], ['mw_transactions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rental_income_date', 'rental_income', ['received_date'], unique=False)
    op.create_index('idx_rental_income_property', 'rental_income', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rental_income_property', table_name='rental_income')
    op.drop_index('idx_rental_income_date', table_name='rental_income')
    op.drop_table('rental_income')
    op.drop_index('idx_realized_gains_year', table_name='realized_gains')
    op.drop_index('idx_realized_gains_sale_tx', table_name='realized_gains')
    op.drop_index('idx_realized_gains_asset', table_name='realized_gains')
    op.drop_table('realized_gains')
    op.drop_index('idx_property_expenses_property', table_name='property_expenses')
    op.drop_index('idx_property_expenses_date', table_name='property_expenses')
    op.drop_table('property_expenses')
    op.drop_index('idx_pension_contributions_plan', table_name='pension_contributions')
    op.drop_index('idx_pension_contributions_date', table_name='pension_contributions')
    op.drop_table('pension_contributions')
    op.drop_table('mw_transaction_tags')
    op.drop_index('idx_mortgage_payments_mortgage', table_name='mortgage_payments')
    op.drop_index('idx_mortgage_payments_date', table_name='mortgage_payments')
    op.drop_table('mortgage_payments')
    op.drop_index('idx_income_records_source', table_name='income_records')
    op.drop_index('idx_income_records_date', table_name='income_records')
    op.drop_table('income_records')
    op.drop_index('idx_credit_payments_date', table_name='credit_payments')
    op.drop_index('idx_credit_payments_account', table_name='credit_payments')
    op.drop_table('credit_payments')
    op.drop_table('transaction_tags')
    op.drop_index('idx_tax_lots_open', table_name='tax_lots')
    op.drop_index('idx_tax_lots_asset', table_name='tax_lots')
    op.drop_table('tax_lots')
    op.drop_table('recurring_expenses')
    op.drop_index('idx_mw_tx_type', table_name='mw_transactions')
    op.drop_index('idx_mw_tx_date', table_name='mw_transactions')
    op.drop_index('idx_mw_tx_category', table_name='mw_transactions')
    op.drop_index('idx_mw_tx_account', table_name='mw_transactions')
    op.drop_table('mw_transactions')
    op.drop_index('idx_credit_statements_account', table_name='credit_statements')
    op.drop_table('credit_statements')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_asset_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('spending_patterns')
    op.drop_index('idx_sim_results_sim_date', table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_table('simulation_params')
    op.drop_table('simulation_events')
    op.drop_table('scenarios')
    op.drop_index('idx_property_valuations_property', table_name='property_valuations')
    op.drop_index('idx_property_valuations_date', table_name='property_valuations')
    op.drop_table('property_valuations')
    op.drop_index('idx_price_history_asset_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_price_fetch_logs_status', table_name='price_fetch_logs')
    op.drop_index('idx_price_fetch_logs_date', table_name='price_fetch_logs')
    op.drop_table('price_fetch_logs')
    op.drop_index('idx_pension_valuations_plan_date', table_name='pension_valuations')
    op.drop_table('pension_valuations')
    op.drop_table('note_tags')
    op.drop_table('mw_payees')
    op.drop_table('mortgages')
    op.drop_table('monte_carlo_runs')
    op.drop_index('idx_market_index_data_date', table_name='market_index_data')
    op.drop_table('market_index_data')
    op.drop_table('income_sources')
    op.drop_table('extraordinary_contributions')
    op.drop_index('idx_dividends_date', table_name='dividends')
    op.drop_index('idx_dividends_asset', table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('credit_accounts')
    op.drop_index('idx_corporate_actions_asset', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('contributions')
    op.drop_index('idx_budgets_period', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('idx_asset_snapshot_date', table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    op.drop_index('idx_alert_history_status', table_name='alert_history')
    op.drop_index('idx_alert_history_rule', table_name='alert_history')
    op.drop_index('idx_alert_history_date', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_table('user_preferences')
    op.drop_table('tax_reports')
    op.drop_table('tags')
    op.drop_table('social_security_estimates')
    op.drop_index('idx_simulations_active', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('idx_scheduled_tasks_type', table_name='scheduled_tasks')
    op.drop_index('idx_scheduled_tasks_status', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_table('report_templates')
    op.drop_table('properties')
    op.drop_table('pension_plans')
    op.drop_index('idx_parameters_category', table_name='parameters')
    op.drop_table('parameters')
    op.drop_index('idx_param_history_key', table_name='parameter_history')
    op.drop_index('idx_param_history_date', table_name='parameter_history')
    op.drop_table('parameter_history')
    op.drop_table('objectives')
    op.drop_index('idx_notes_entity', table_name='notes')
    op.drop_index('idx_notes_date', table_name='notes')
    op.drop_table('notes')
    op.drop_index('idx_networth_date', table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_table('net_worth_milestones')
    op.drop_table('mw_categories')
    op.drop_table('mw_accounts')
    op.drop_index('idx_monthly_summaries_period', table_name='monthly_summaries')
    op.drop_table('monthly_summaries')
    op.drop_table('market_indices')
    op.drop_index('idx_import_batches_status', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('idx_exchange_rate_pair', table_name='exchange_rates')
    op.drop_index('idx_exchange_rate_date', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_table('dashboard_widgets')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_date', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('assets')
    op.drop_table('app_versions')
    op.drop_table('api_keys')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
