"""add_shares_mw_symbol_to_mw_transactions

Revision ID: f7f65a8daa5f
Revises: 261466931cbd
Create Date: 2026-03-28 08:38:28.320304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f65a8daa5f'
down_revision: Union[str, None] = '261466931cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_transactions', sa.Column('shares', sa.Numeric(precision=16, scale=8), nullable=True))
    op.add_column('mw_transactions', sa.Column('mw_symbol', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_transactions', 'mw_symbol')
    op.drop_column('mw_transactions', 'shares')
    # ### end Alembic commands ###
